sudo: false
language: python
python:
  - "3.6"
install:
  - pip install .
  - pip install -r requirements.txt
script: pytest --cov toapi --cov-report term-missing

after_success:
  - codecov
branches:
  only:
    - master