sudo: false
language: python
python:
  - "3.6"
install:
  - pip install .
  - pip install -r requirements.txt
script: pytest tests --pep8 toapi -v --cov toapi --cov-report term-missing

branches:
  only:
    - master